"""empty message

Revision ID: 221647278093
Revises: ed9e8559a184
Create Date: 2023-05-23 19:47:45.674660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221647278093'
down_revision = 'ed9e8559a184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=250), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
